apiVersion: v1
kind: Service
metadata:
  name: kibana-service
  labels:
    app: kibana
spec:
  ports:
    - port: 5601
      targetPort: 5601
      protocol: TCP
  selector:
    app: kibana
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: kube-system
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:8.15.2
          env:
            - name: ELASTICSEARCH_HOSTS
              value: http://elasticsearch:9200  # Elasticsearch 서비스 주소
          ports:
            - containerPort: 5601
          readinessProbe:
            httpGet:
              path: /
              port: 5601
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 5601
            initialDelaySeconds: 30
            periodSeconds: 10
---
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: kibana-ingressroute
  namespace: kube-system
spec:
  entryPoints:
    - web  # HTTP 접속을 위한 entryPoint (HTTP일 경우)
    # - websecure  # HTTPS 접속을 위한 entryPoint (HTTPS일 경우)
  routes:
    - match: Host(`kibana.example.com`)  # 접속할 도메인
      kind: Rule
      services:
        - name: kibana-service  # Elasticsearch 서비스 이름
          port: 9200  # Elasticsearch HTTP 포트
