apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-secret  # Secret의 이름
  namespace: kube-system      # Fluentd DaemonSet과 같은 네임스페이스
type: Opaque
data:
  username: c3RlcHBvZA==  # base64 인코딩된 사용자 이름 (예: steppod)
  password: c3RlcHBvZDEyMw==  # base64 인코딩된 비밀번호 (예: steppod123)